### ISSUE TITLE
Todo before blacklist feature

### ISSUE THREAD

**Issue by mindofmar** [mindofmar/wallet-guard#35]
Merge & release fix for checking 'contains' (>5 characters) https://github.com/mindofmar/wallet-guard/issues/26 
- [ ] fixed in https://github.com/mindofmar/wallet-guard/pull/33
- [ ] Release on chrome store

Fix 'big tech' issues https://github.com/mindofmar/wallet-guard/issues/21
- [ ] Move them to a separate whitelist so that they aren't checked with the normal web3 algo
